# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZPxKWkkOuce5f8H_UmoqtBIcjNB3jmCf
"""

num = input()
a=num
digit=int(num)
if (digit%3==0) or (digit%5==0) or (digit%7==0) or ('3' in num) or ('5' in num) or ('7' in num):
  a =""
  if (digit%3==0):
    a ="Jugs"
  if (digit%5==0):
    a = a+"Mugs"
  if (digit%7==0):
    a =a+"Pugs"

print(a)

num = int(input())
rev = bool(input())
for i in range(1,num+1):
  if rev:
    string = 'Jugs' * bool(i%3==0 or '3' in str(i))
    string = 'Mugs' * bool(i%5==0 or '5' in str(i)) + string
    string = 'Pugs' * bool(i%7==0 or '7' in str(i)) + string
    print( string or i)
  else:
    print("Jugs" * (i%3==0 or '3' in str(i)) + "Mugs" * (i%5==0 or '5' in str(i)) + "Pugs" * (i%7==0 or '7' in str(i)))

num = int(input())
rev = input().lower() == "true"

if rev:
    for i in range(num, 0, -1):
        string = ""
        string += 'Jugs' * bool(i % 3 == 0 or '3' in str(i))
        string += 'Mugs' * bool(i % 5 == 0 or '5' in str(i))
        string += 'Pugs' * bool(i % 7 == 0 or '7' in str(i))
        print(string or i)
else:
    for i in range(1, num + 1):
        print("Jugs" * (i % 3 == 0 or '3' in str(i)) + "Mugs" * (i % 5 == 0 or '5' in str(i)) + "Pugs" * (
                    i % 7 == 0 or '7' in str(i)))

